# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET projects

on:
  push:
    paths-ignore:
      - "**/*.docs"
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: SRC/Web/package-lock.json

      - name: Install Node.js dependencies
        working-directory: SRC/Web
        run: npm install

      - name: Build Tailwind CSS
        working-directory: SRC/Web
        run: npm run build:css

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Create Test Results Directory
        run: mkdir -p TestResults

      - name: Run all tests in all test projects
        run: |
          timestamp=$(date +%s)
          for proj in $(find . -name "*.csproj" -path "*/Tests/*"); do
            name=$(basename "$proj" .csproj)
            filename="${name}_${timestamp}.trx"
            # Use a relative results directory so the container writes into the mounted workspace
            dotnet test "$proj" --no-build --no-restore --logger "trx;LogFileName=${filename}" --results-directory "TestResults/"
          done

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TailwindBlog-Test-Results
          path: TestResults

      - name: Codecov
        if: github.actor != 'nektos/act'
        uses: codecov/codecov-action@v5.4.3

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && github.actor != 'nektos/act' }}
        uses: codecov/test-results-action@v1

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        # When running locally with act the GITHUB_ACTOR is 'nektos/act' and
        # the runner can't access GitHub's API for local commit SHAs. Skip
        # publishing test results (which queries commits/pull requests) in
        # that case to avoid 403/422 API errors.
        if: always() && github.actor != 'nektos/act'
        with:
          # Disable creating GitHub check runs when running locally with act
          # (this avoids the "You must authenticate via a GitHub App" 403 error
          # that happens because act can't emulate GitHub App authentication).
          check_run: false
          files: |
            TestResults/**/*.trx

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install GitVersion
        if: github.actor != 'nektos/act'
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: "6.0.x"

      - name: Use GitVersion
        if: github.actor != 'nektos/act'
        id: gitversion # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.1.0

      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        if: github.actor != 'nektos/act'
